name: Build and Attach Binaries to Release

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Assure que Git récupère bien tous les tags pour identifier la release
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Execute build script
        run: ./build.sh

      - name: Upload Binaries to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            build/packly-linux
            build/packly-windows.exe
            build/packly-macos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
